### ISSUE TITLE
How to use this module to build something on top of it?

### ISSUE THREAD

**Issue by jalotra** [JaroslawWiosna/level-set#31]
Hey 
I am trying to segment out red blood cells pictures from a microscope picture using level-set algorithms. What things are needed to be done on top of this module to get contours on all the rbcs present.

This is the example photo:
![Frog-blood-400x](https://user-images.githubusercontent.com/39359593/62830232-257ada00-bc29-11e9-8fde-e513cbb7c27b.jpg)
.
This is the result I am getting right now:
![phi](https://user-images.githubusercontent.com/39359593/62830241-3af00400-bc29-11e9-9823-f34efef09584.jpg)

**Comment by JaroslawWiosna** [comment]
@jalotra 
Hello,

so first of all you have to use larger image.

![ls_large](https://user-images.githubusercontent.com/11769750/62835685-8c18eb80-bc5b-11e9-9625-454967109d74.jpg)

then you have to modify parameters. I used the following:

```bash
level-set -i ls_large.jpg -mi 0.5 -eta 0.02 -lambda1 1 -lambda2 1 -eps 0.1 -dt 0.0001 -steps 2
```

`ls_large.jpg` is the input image ofc.

---

As a result this file is created:

![phi](https://user-images.githubusercontent.com/11769750/62835717-d601d180-bc5b-11e9-8ce7-241850e628d6.jpg)

---

If you want more information about parameters, please read papers from README.md

**Comment by jalotra** [comment]
Thankyou @JaroslawWiosna . I am going to read all the papers, can you tell me if there is a method not to change the color space of the input image? And by a larger size what threshold dimensions are you talking about?  
I may bug you some more times. : )

**Comment by JaroslawWiosna** [comment]
@jalotra 
> can you tell me if there is a method not to change the color space of the input image? 

If I got you right, you are asking me if the output image can have an original background instead of black canvas? Unfortunately, this software does not support it.

> And by a larger size what threshold dimensions are you talking about?

I changed the size to 1000x751

Yeah, feel free to ask questions :)

**Comment by jalotra** [comment]
Okay @JaroslawWiosna . So the algorithm doesn't support the RGB channels or you have implemented something? And if I want to keep intact the original color channels what all has to be changed?

**Comment by JaroslawWiosna** [comment]
The implementation does not support RGB.
The hack is to read pictures in greyscale.

This is copy-paste from constructor of `Image`
```
flag - default value is equal to cv::IMREAD_GRAYSCALE
```

**Comment by jalotra** [comment]
Thank you @JaroslawWiosna  for the support. Have to find another way to do this. If you know of any paper that implements the same level-set algo as yours but builds upon colored channels then please let me know.The one paper I found out was implementing adaptive-level-set algorithm but I want to build upon your code as I don't want to code everything from scratch.

**Comment by JaroslawWiosna** [comment]
@jalotra Happy to help.
To be honest I also expect more of this approach. As you can see this project is dead for 3 years now.
I don't know any other papers. I've put everything in README.md, so I am afraid I can't help.

This project is under MPL licence, so as far as I know you can do whatever you want with this code, but it would be great if you will notify me what have you change. Basically, feel free to modify the code and I would be happy to know if you manage to succeed. :-)

**Comment by jalotra** [comment]
Yup I will notify you with all the code that I used. Thanks for the support.
